<a href="https://colab.research.google.com/github/Adwait-aayush/Learning-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:

array=np.array([[1,2,4],[2,3,4]])
print(array)

[[1 2 4]
 [2 3 4]]


In [ ]:
array1=np.array(i for i in range(0,10,2))
print(array1)

<generator object <genexpr> at 0x7c41b10876b0>


In [ ]:
c=np.array([[1,2,3],[4,5,6]],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
zeroes_array=np.zeros((4,5)) #4 and 5 are the dimensions respectively
print(zeroes_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#to create arrays of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#to create arrays of a fixed value full is used and then the value is specified
z=np.full((3,3),4)
print(z)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [14]:
#identity matrix

ar=np.eye((2))
print(ar)

[[1. 0.]
 [0. 1.]]


In [16]:
#to create array of random values np.random.random fn is used
b=np.random.random((2,3))

print(b)

[[0.33220964 0.74457607 0.09769842]
 [0.38852208 0.66713753 0.9219445 ]]


In [17]:
# to create a random matrix of int within the specifeid range the np.random.ranodmint fn is used syntax--np.random.randomint(starting value,ending value,(dimension1,dimension2))
c=np.random.randint(1,20,(3,3))
print(c)

[[ 6 18 15]
 [14 18 19]
 [13 16  3]]


In [18]:
#to get array of evenly spaced integers np.linspace(min_val,max_val,number of values we want)
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [21]:
# convert list to array by np.asarray()

list=[1,2,3,4,5]
e=np.asarray(list,dtype=float)
print(d)

[10. 15. 20. 25. 30.]


In [22]:
#analyse the array

c=np.random.randint(1,20,(5,5))
print(c)
#dimension
print(c.shape)
#number of dimensions
print(c.ndim)
#no of elemenst
print(c.size)
# datatype
print(c.dtype)

[[18 18  2  8 14]
 [ 4 14 16 17 10]
 [13  2 15 17  2]
 [ 3  5 17 11 15]
 [11  4  9  3  8]]
(5, 5)
2
25
int64


In [26]:
#mathematical operations on numpy array

a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

print(a+b) #element wise addition does not concatenate similar multiply sub and div
print(np.add(a,b))

print(a-b)
print(np.subtract(a,b))

print(a*b)
print(np.multiply(a,b))

print(a/b)
print(np.divide(a,b))

[[9 9 7]
 [5 4 9]
 [0 1 8]]
[[12 19 14]
 [14 18 16]
 [13 11 15]]
[[21 28 21]
 [19 22 25]
 [13 12 23]]
[[21 28 21]
 [19 22 25]
 [13 12 23]]
[[ -3 -10  -7]
 [ -9 -14  -7]
 [-13 -10  -7]]
[[ -3 -10  -7]
 [ -9 -14  -7]
 [-13 -10  -7]]
[[108 171  98]
 [ 70  72 144]
 [  0  11 120]]
[[108 171  98]
 [ 70  72 144]
 [  0  11 120]]
[[0.75       0.47368421 0.5       ]
 [0.35714286 0.22222222 0.5625    ]
 [0.         0.09090909 0.53333333]]
[[0.75       0.47368421 0.5       ]
 [0.35714286 0.22222222 0.5625    ]
 [0.         0.09090909 0.53333333]]


In [27]:
#array manupulation

array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 5 4]
 [5 8 7]]
(2, 3)


In [28]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[5 5]
 [5 8]
 [4 7]]
(3, 2)
