<a href="https://colab.research.google.com/github/Adwait-aayush/Learning-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array=np.array([[1,2,4],[2,3,4]])
print(array)

[[1 2 4]
 [2 3 4]]


In [ ]:
array1=np.array(i for i in range(0,10,2))
print(array1)

<generator object <genexpr> at 0x7c41b10876b0>


In [ ]:
c=np.array([[1,2,3],[4,5,6]],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
zeroes_array=np.zeros((4,5)) #4 and 5 are the dimensions respectively
print(zeroes_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
